name: waydroid
version: "1.3.3"
summary: Android™ application support
description: |
  Waydroid uses a container-based approach to boot a full Android system on a regular GNU/Linux system like Ubuntu.

base: core20
confinement: devmode
grade: devel

apps:
  waydroid:
    command: waydroid

parts:
  waydroid:
    plugin: autotools
    source: .
    stage-packages:
      - lxc
      - python3-gi
      - gir1.2-gtk-3.0
    python-packages:
      - gbinder-python
    
  python3-gbinder:
    plugin: python
    source: https://github.com/erfanoabdi/gbinder-python
